# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'South Platte Data Platform Project'
pages:
- Introduction: index.md
- Project Coordination: project-coordination.md
- Datasets: datasets.md
- Visualizations: visualizations.md
- Stories: stories.md
- Resources: resources.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-proj-south-platte-data-platform
site_description:  'South Platte Data Platform Project'
site_author:  'Open Water Foundation'
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  'Copyright Open Water Foundation'
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
